AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Doit AppMod Lab1 running on Lambda
Parameters:
  SGID:
    Description: EC2 Security Group for datastore ingress
    Type: String
  SUBNETIDS:
    Description: VPC Subnets
    Type: CommaDelimitedList
  INSTANCEENDPOINT:
    Description: The RDS Endpoint
    Type: String

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'DoitLab1Lambda'
      CodeUri: src
      Handler: app.handler
      Runtime: python3.9
      Timeout: 10
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
      Environment:
        Variables:
          DBA_USER: api
          DBA_PASSWD: Doit#Lab1@2023
          INSTANCE_ENDPOINT:
            !Ref INSTANCEENDPOINT
          DATABASE: lab1

      VpcConfig:
        SecurityGroupIds:
          - !Ref SGID
        SubnetIds:
            !Ref SUBNETIDS

  Api:
    Type: AWS::Serverless::HttpApi

Outputs:
  ApiUrl:
    Description: URL of your API
    Value:
      Fn::Sub: 'https://${Api}.execute-api.${AWS::Region}.${AWS::URLSuffix}/'
